/* Generated by tools/fetch-prospectuses.mjs. Do not edit by hand.
 * Maps institution id → locally mirrored prospectus PDF. */
window.PROSPECTUS_LOCAL = {
  "up": {
    "file": "prospectuses/up-2027-undergraduate-prospectus.pdf",
    "size": 3681547,
    "source": "https://drupalwebprod-files.up.ac.za/Public/2026-01/UP_UG%20Prospectus%202027_NSC-IEB_DevV5_web_0.pdf",
    "year": 2027,
    "fetched": "2026-09-30"
  },
  "su": {
    "file": "prospectuses/su-2027-undergraduate-prospectus.pdf",
    "size": 902167,
    "source": "https://files.su.ac.za/public/undergraduate-maties/documents/2026-01/su-admissions-booklet-2027.pdf",
    "year": 2027,
    "fetched": "2026-09-30"
  },
  "ru": {
    "file": "prospectuses/ru-2027-undergraduate-prospectus.pdf",
    "size": 4413704,
    "source": "https://www.ru.ac.za/media/rhodesuniversity/content/registrar/documents/information/studentrecruitment/RU_READY_Undergraduate_Prospectus_2026_DIGITAL_A5_Landscape_24pp_18Mar2026.pdf",
    "year": 2027,
    "fetched": "2026-09-30"
  },
  "wsu": {
    "file": "prospectuses/wsu-2027-undergraduate-prospectus.pdf",
    "size": 426037,
    "source": "https://wsu.ac.za/media/attachments/2026/05/27/2027-information-brochure-admission-requirements.pdf",
    "year": 2027,
    "fetched": "2026-09-30"
  },
  "ul": {
    "file": "prospectuses/ul-2027-undergraduate-prospectus.pdf",
    "size": 2269016,
    "source": "https://www.ul.ac.za/wp-content/uploads/2025/03/Undergraduate-Prospectus-2027.pdf",
    "year": 2027,
    "fetched": "2026-09-30"
  }
};
